
#################################
# Port Number
#################################
server:
  port: 83
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

org:
  zerock:
    upload:
      path: "C:\\upload"

spring:
  servlet:
    multipart:
      enabled: 'true'
      max-request-size: 30MB
      max-file-size: 10MB
      location: C:\upload
  banner:
    location: banner/banner.txt

  application:
    name: PipProject

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    cache: false
    encoding: UTF-8

  #################################
  # MySQL Setting
  #################################
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bootex?serverTimezone=UTC
    username: root
    password: 1234

  #################################
  # JPA Setting
  #################################
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update #update? ??? ?? ??? ?, ???? ??
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  jackson:
    serialization:
      fail-on-empty-beans: false



  ###############################
  # Security User
  ###############################
  security:
    user:
      name: test@test.com
      password: 1111

###############################
# Log info
###############################
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace